config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do # this removes the get "users/new" line--because resources :users doesn’t just add a working /users/1 URI, it endows our application with all the actions needed for a RESTful Users resource, along with a large number of named routes for generating user URIs
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy] # this is a resource to get the standard RESTful actions for sessions (since Sessions does not have a need to show or edit sessions, we’ve restricted the actions to new, create, and destroy using the :only option)
  resources :microposts, only: [:create, :destroy] # routes for the microposts resource
  resources :relationships, only: [:create, :destroy] # routes for user relationships

  root :to => 'static_pages#home' # call using root_path --> setting it as our default page

  match '/help', to: 'static_pages#help' # call using help_path
  match '/about', to: 'static_pages#about' # call using about_path
  match '/contact', to: 'static_pages#contact' # call using contact_path

  match '/signup', to: 'users#new' # call using signup_path
  match '/signin', to: 'sessions#new' # call using signin_path
  match '/signout', to: 'sessions#destroy', via: :delete # call using signout_path, the "via: :delete" indicates that this path should be invoked using an HTTP DELETE request

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <%
      # @user.errors.full_messages.each do |msg|
      object.errors.full_messages.each do |msg| # changed from the above to work with other objects
    %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<!-- status feed partial -->

<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<!-- partial for a single feed item -->

<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <%= render 'shared/micropost', :micropost => feed_item %>
</li>

app/views/shared/_gravatarH1.html.erb
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>

app/views/shared/_micropost.html.erb
  <span class="content"><%= wrap(micropost.content) %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
  <% if current_user?(micropost.user) %><!-- adding a delete link to the micropost partial -->
    <%= link_to "delete", micropost, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: micropost.content %>
  <% end %>

app/views/shared/_micropost_form.html.erb
<!-- form partial for creating microposts -->

<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<!-- partial for the user info sidebar -->
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user, size: 52 %>
</a>
<h1><%= current_user.name %></h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>